export const statesData = {"delhiColonies" : [
    "Connaught Place",
    "Hauz Khas",
    "South Extension",
    "Vasant Kunj",
    "Greater Kailash",
    "Rajouri Garden",
    "Karol Bagh",
    "Paharganj",
    "Chandni Chowk",
    "Dwarka",
    "Janakpuri",
    "Rohini",
    "Pitampura",
    "Shalimar Bagh",
    "Saket",
    "Lajpat Nagar",
    "Green Park",
    "Defence Colony",
    "Paschim Vihar",
    "Malviya Nagar",
    "Preet Vihar",
    "Mangar",
    "Sarai Rohilla",
    "Kalkaji",
    "Bengali Market",
    "Mayur Vihar",
    "Nehru Place",
    "Vikaspuri",
    "Jangpura",
    "Kalkaji",
    "Sarai Kale Khan",
    "Sadar Bazaar",
    "Delhi Cantonment",
    "Mundka",
    "Lajpat Nagar",
    "Okhla",
    "Sarai Rohilla",
    "Anand Vihar",
    "Shahdara",
    "Vasant Vihar",
    "Pitam Pura",
    "Sadar Bazar"
],
 "haryanaCities" : [
    "Ambala",
    "Bhiwani",
    "Faridabad",
    "Fatehabad",
    "Gurugram",
    "Hisar",
    "Jind",
    "Karnal",
    "Kaithal",
    "Mahendragarh",
    "Panchkula",
    "Panipat",
    "Rewari",
    "Sirsa",
    "Sonipat",
    "Yamunanagar",
    "Rohtak",
    "Jhajjar",
    "Charkhi Dadri",
    "Palwal",
    "Kurukshetra",
    "Nuh",
    "Mewat",
    "Gohana",
    "Shahbad",
    "Tosham",
    "Hansi",
    "Barwala",
    "Gurgaon",
    "Bawal",
    "Jind",
    "Assandh"
],
 "rajasthanCities" : [
    "Jaipur",
    "Udaipur",
    "Jodhpur",
    "Kota",
    "Bikaner",
    "Ajmer",
    "Alwar",
    "Sikar",
    "Bhilwara",
    "Pali",
    "Tonk",
    "Sri Ganganagar",
    "Hanumangarh",
    "Jhunjhunu",
    "Chittorgarh",
    "Barmer",
    "Dausa",
    "Nagaur",
    "Ratangarh",
    "Jaisalmer",
    "Sawai Madhopur",
    "Jalore",
    "Sirohi",
    "Bundi",
    "Dungarpur",
    "Jhalawar",
    "Rajsamand",
    "Banswara",
    "Karauli",
    "Pratapgarh",
    "Rajnagar",
    "Phalodi",
    "Kekri",
    "Sangaria",
    "Pushkar",
    "Mandawa",
    "Mount Abu",
    "Neemrana",
    "Sangaria",
    "Nohar"
]} 
